language: python
python:
- 3.4
install:
- pip install -r requirements-dev.txt
- pip install .
deploy:
  provider: pypi
  user: cpapazaf
  password: 
    secure: "CAZ+BsCJFLUPy0w5SuEuU8+0kYFS/PGB8SvN28XAZlDWytzRYDpAPi31Q3uGeUY/I2X+NEZQcWMIJl4TeOf/ApTpNgA1C7B2G8KBywV7homgMQrGDIFSLc8VYz3ogJORbFby7UpFbaLLCX4qGeg0clzw8y8AKzo0jjzJCAfcbIYR7b8JumO9/+N3WDMz1Kgn3hjD32Pu6b/sNs4vdNH3eyITk4SZBkW0KtGdmIKAritTZm+RG2J6X3riTdkAUPFAdnnIF+Af8qTdCbyuTw3skWVPBx/HcGhiuK0lsZkIRYdwz/e4Chn8Sp7U/OTfN+HLPIzdKsbahXCBCP3QoqeaqGRzD/Bl4nbKwrP/WTuev6f0kov/l+NfNH7pf/TE+4dQ9qhHa87TFckkY2exJ8P2pDspJada9suhG15IIV5VvT6vAardyFk6JVpzOWp3/tMpW5otCy5/Q3USXrxo+h0uDWK5CL5bzXT6tLHXas+aXFi0v1t6I64TdV831eAnmADfgcPPRqQ5SUoO+kgf1faaCuBSZECp9O6cyqF5ktC0ZrHhJ6VsrlotmuqA08yoJcm/VnBThqhkXvuabYB50Iq2SChKpM2w1YOIaPUaPxAOjuQe2XQ7AsTgoDHCwkHSRKtYAwPnn6Dwy1NzVTIk2wUn9wLMDK2tiFEqWfeE9xgUcc8=" 
  on:
    tags: true
    branch: master
script:
- py.test --cov-report= --cov=soners soners/test/*
- pylama .
after_success:
- coverals
- if [ $TRAVIS_TAG ]; then curl -X POST https://readthedocs.org/build/soners; fi
