language: python
python:
  - 3.4
install:
  - pip install -r requirements-dev.txt
  - pip install .
script:
  - py.test --cov-report= --cov=soners soners/test/*
  - pylama .
deploy:
    # test pypi
  - provider: pypi
    distributions: sdist
    server: https://testpypi.python.org/pypi
    user: "cpapazaf"
    password:
      secure: "qr6Yg8b84k27t+nXnUguAMbUEtz4ksFWU+CkG56Yo9CPUm1fSNA1V8t705sahpTYuF7RqtWLcbG7AidFma8jyYJgQfwGs+Np/RaxtbVYAoFpnesS7GceNuRSnIMjRgn4mPynmCdwWi9KAMBhqhyp3SoKVj3aMj+HmplYD1Nh3pOJpiLg3OBfvRYPP1eOtN3fyhb5P5jxwz+NpP6zsb33fI9EYbxTxpUOTfrWf5xcyYRSCQwdLgXO5I5YP/gcWRzo18Vvlo+fR/EaQOJx88eMZ1JjKiw3pPn/erThCEcBj2hVAVKmEK3NpC+EJwevHgryAcDNIR6DMcpifg7I1DTiocn6Gi4jD96HMgeShHmM0qTLYzffM8U52u3mKSqHuWG92bUodxh9If3CkYsB83+9oTwQwWyIvXwlYnycTh7/7b7mzs9RRDPtfrK4dCX5kRbfHxjay/tJIWMs6Scg+lFXP1aHaihLSVpjnwGO/jeyUujsHkdaQIaVvjTvV1djaZyfWjgj/k5k+CXBWF5laRtuicGPxKR8FSOSfUXDaRP2AjMvs6e43jRHXfJPEm6/larsFHqkHky1ahXFUMa+c3GZAnQ6sWsQRQFnnVpvJxWTgZrbwRtC38U1iLgGGy1mx+gmXBKjFqW+Q6ijN/uBgsN4CKzqG7Bhc3eediSEcf86MuQ="
    on:
      tags: false
      branch: master
      condition: $TRAVIS_PYTHON_VERSION = "3.4"
    # production pypi
  - provider: pypi
    distributions: sdist
    user: "cpapazaf"
    password:
      secure: "qr6Yg8b84k27t+nXnUguAMbUEtz4ksFWU+CkG56Yo9CPUm1fSNA1V8t705sahpTYuF7RqtWLcbG7AidFma8jyYJgQfwGs+Np/RaxtbVYAoFpnesS7GceNuRSnIMjRgn4mPynmCdwWi9KAMBhqhyp3SoKVj3aMj+HmplYD1Nh3pOJpiLg3OBfvRYPP1eOtN3fyhb5P5jxwz+NpP6zsb33fI9EYbxTxpUOTfrWf5xcyYRSCQwdLgXO5I5YP/gcWRzo18Vvlo+fR/EaQOJx88eMZ1JjKiw3pPn/erThCEcBj2hVAVKmEK3NpC+EJwevHgryAcDNIR6DMcpifg7I1DTiocn6Gi4jD96HMgeShHmM0qTLYzffM8U52u3mKSqHuWG92bUodxh9If3CkYsB83+9oTwQwWyIvXwlYnycTh7/7b7mzs9RRDPtfrK4dCX5kRbfHxjay/tJIWMs6Scg+lFXP1aHaihLSVpjnwGO/jeyUujsHkdaQIaVvjTvV1djaZyfWjgj/k5k+CXBWF5laRtuicGPxKR8FSOSfUXDaRP2AjMvs6e43jRHXfJPEm6/larsFHqkHky1ahXFUMa+c3GZAnQ6sWsQRQFnnVpvJxWTgZrbwRtC38U1iLgGGy1mx+gmXBKjFqW+Q6ijN/uBgsN4CKzqG7Bhc3eediSEcf86MuQ="
    on:
      tags: true
      branch: master
      condition: $TRAVIS_PYTHON_VERSION = "3.4"
after_success:
  - coverals
  - if [ $TRAVIS_TAG ]; then curl -X POST https://readthedocs.org/build/soners; fi
