language: python
python:
- 3.4
install:
- pip install -r requirements-dev.txt
- pip install .
deploy:
  provider: pypi
  user: cpapazaf
  password: aEyMJu2DmwYGsV6XXjfzH/Tf6A3TZl3DkQSPysvZZzQvTfMxb2WU837SBUuyCGiDfG86H4z3GtdSlzTuRaVdMZgjA2GtnpC1V3YNo8vnQnV0WXkixVDJwtDL3zVgkd4a+4pPijnODE4Zp2W7LvXLXcCjw5cjL5uxd96kb4NBmX7evSXi7tjaGCZMyw3tFTzh61LN2YWHUuFkbpHqv3YqnH7VslzAO7/soMGY2vICkbQJH40oOliQ9MeGesCuLExcHWTCrZ19pHpXsD/FsWXX0cHe05R/e3UNj98sSxP3W33yYEcIYZmHcI2u4Gqoa0HY0IEGlCobKZodP4WGLReogAkab5ysCBWKrwabWz6/N4dX36S1nGcsonp0Du9lAUBnhBdJLoM3QfzfWNVsstdzvtTXW/ggiG160tE8dOHI6698GGum4VeMAV6VR6huGnLKI9djFW0QSCCnzarOlHlc260L5NqUulOUQ+odetWt/Q7EBIkhV+BHp66katJs2nsOuKwktM24dacXHYApddhcrWSi+4FLSB2kpjS8K2SsYk0ZDiZxqDsBjFeQUO27TG1u1bcILE+0+uowITOA0d4avEMl6mBvRtKDpiu2YrYYyEE2lt4Z3YEHSP1IXmoiOYVOy3GwoNZ57S4eL4o9Wder160MmcrapmrL1PMYGp1nmS4=
  on:
    tags: true
    branch: master
script:
- py.test --cov-report= --cov=soners soners/test/*
- pylama .
after_success:
- coverals
- if [ $TRAVIS_TAG ]; then curl -X POST https://readthedocs.org/build/soners; fi
