language: python
python:
- 3.4
install:
- pip install -r requirements-dev.txt
- pip install .
deploy:
  provider: pypi
  user: cpapazaf
  password:
    secure: jhytSGVXCmLCGWZTsahbVKGXsp3HdR+PJFK8u3TnL1x4g+S6pdZoHc9SMFDvDtMdBvDmaryQyaXKGfD6Nc/dfOfP4hJuzOvEeJfQOjpZzNpzaFgdA61eKEuiB/9MghCNcmljeW0XEcujkbj2y22qQM7Gqc7ejv3DAgzzs+MTY3kEXh3tM8nfTfibF8wB8iCwsHBFFOD7QNZL3fPFdwEsgnsYYaqGvi+dd44XtHAAJ/X/s67rixFrsavpbPAZH7hOq0eOHJ+GyvlRTH5b0mlcTywlZqTnHVCiN8zWaTdZksMMf9KcbquBwAAinmXImor9hZINvewpB40gnk/1p1zxD9jFpcYOwYwBwWprthWSCSxYFvfu84PIgXcFn3f7POdzWG2qyZSsIuXUmffCCX8+TNulG0dYMZZoxxrNeaoyA2wBqfS9Ag4vUM7FRfN+VxUxeazW1zAFQu7OILvtF+q18t5w6nKrjfpHDNSLUQqtE2a5Jpz7WKLI012y7rGgHoV6oluFhZ+mSAyZu6Rk8yJD+W+8cZc8iAIrBSFhFsWnZxJU5+Linf4iH6etautctkbbojPWeVEjekNeMguSZbysuB02zHcCz7PHtDIKt1XRyeFKl/2S+DkRZsONVzA/JeizJkOHI7huqFpNS5lyxXp3Jqjiz7ckRJdKFuQCZCt9UT8=
  on:
    tags: true
    branch: master
script:
- py.test --cov-report= --cov=soners soners/test/*
- pylama .
after_success:
- coverals
- if [ $TRAVIS_TAG ]; then curl -X POST https://readthedocs.org/build/soners; fi
